package utils

import "github.com/phpdave11/gofpdf"

// PDFDocument is a narrow contract for PDF generators.
type PDFDocument interface {
	Build() error
}

// NewPDFWithDefaults creates a PDF with common metadata/header settings.
func NewPDFWithDefaults(title string) *gofpdf.Fpdf {
	pdf := gofpdf.New("P", "mm", "A4", "")
	SetPDFMetadata(pdf, title)
	return pdf
}

// SetPDFMetadata applies common meta info to PDFs generated by the app.
func SetPDFMetadata(pdf *gofpdf.Fpdf, title string) {
	if pdf == nil {
		return
	}
	pdf.SetTitle(title, false)
	pdf.SetAuthor("Travel App", false)
	pdf.SetCreator("Travel App", false)
}
